In [2]:
import numpy as np
from scipy import stats
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [3]:
df= pd.read_csv("C:/Users/luxha/Python data 101/Data Buat Latihan/biking/hour.csv")

In [12]:
df[df['day']=='Sunday'].head(10)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt,day
24,25,2011-01-02,1,0,1,0,0,0,0,2,0.46,0.4545,0.88,0.2985,4,13,17,Sunday
25,26,2011-01-02,1,0,1,1,0,0,0,2,0.44,0.4394,0.94,0.2537,1,16,17,Sunday
26,27,2011-01-02,1,0,1,2,0,0,0,2,0.42,0.4242,1.00,0.2836,1,8,9,Sunday
27,28,2011-01-02,1,0,1,3,0,0,0,2,0.46,0.4545,0.94,0.1940,2,4,6,Sunday
28,29,2011-01-02,1,0,1,4,0,0,0,2,0.46,0.4545,0.94,0.1940,2,1,3,Sunday
29,30,2011-01-02,1,0,1,6,0,0,0,3,0.42,0.4242,0.77,0.2985,0,2,2,Sunday
30,31,2011-01-02,1,0,1,7,0,0,0,2,0.40,0.4091,0.76,0.1940,0,1,1,Sunday
31,32,2011-01-02,1,0,1,8,0,0,0,3,0.40,0.4091,0.71,0.2239,0,8,8,Sunday
32,33,2011-01-02,1,0,1,9,0,0,0,2,0.38,0.3939,0.76,0.2239,1,19,20,Sunday
33,34,2011-01-02,1,0,1,10,0,0,0,2,0.36,0.3485,0.81,0.2239,7,46,53,Sunday

In [7]:
def get_day_name(date_str):
    date_obj = datetime.strptime(date_str, '%Y-%m-%d')
    return date_obj.strftime('%A')

In [8]:
df['day'] = df['dteday'].apply(get_day_name) ##untuk masukan data mengenai hari

In [13]:
def detect_outliers(data):
    # Konversi data menjadi numpy array untuk kemudahan perhitungan
    data = np.array(data)
    
    # Hitung Q1 dan Q3
    Q1 = np.percentile(data, 25)
    Q3 = np.percentile(data, 75)
    
    # Hitung IQR
    IQR = Q3 - Q1
    
    # Tentukan batas bawah dan batas atas
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    # Deteksi outlier
    outliers = data[(data < lower_bound) | (data > upper_bound)]
    
    return outliers

# Contoh data
data = [10, 12, 13, 15, 15, 16, 18, 20, 22, 23, 24, 30, 100]

# Panggil fungsi
outliers = detect_outliers(data)

print("Outliers:", outliers)

Outliers: [100]